config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "top" => "homes#top"
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)
    post.save
    redirect_to "/top"
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post.id)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :note)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/homes/top.html.erb
<h1>Topページ<h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>編集</h1>
<h2>テスト</h2>
<%= form_with model:@post, url: post_path(@post), local:true do |f| %>
    <h3>タイトル</h3>
    <%= f.text_field :title %>
    <h3>本文</h3>
    <%= f.text_area :body %>
    <h3>ノート</h3>
    <%= f.text_field :note %>
    <h3>ボタン</h3>
    <%= f.submit "投稿" %>
<% end %>

app/views/posts/index.html.erb
<h1>例</h1>
<% @posts.each do |post| %>
    <h2><%= link_to post.title, post_path(post) %></h2>
    <p><%= post.body %></p>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<h2>テスト<h2>
<%= form_with model:@post, url:"/posts", local:true do |f| %>
<h3>タイトル</h3>
<%= f.text_field :title %>
<h3>本文</h3>
<%= f.text_area :body %>
<h3>ノート</h3>
<%= f.text_field :note %>
<h3>ボタン</h3>
<%= f.submit "投稿" %>
<% end %>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>それぞれの投稿</h1>
<p><%= @post.title %></p>
<p><%= @post.body %></p>
<p><%= @post.note %></p>

<%= link_to '編集する', edit_post_path(@post.id) %><br>
<%= button_to '削除', post_path(@post.id), method: :delete, data: { confirm: '本当に削除しますか？' } %><br>
<%= link_to '投稿一覧ページへ', posts_path %>